### ISSUE TITLE
Support for Panalytical XRDML files

### ISSUE THREAD

**Issue by stupidus89** [wojdyr/xylib#9]
It would be nice to be able to convert Panalytical XRDML files (http://www.panalytical.com/Xray-diffraction-software/Data-Collector/XRDML.htm). These are just xml files. 

I haven't actually looked at the specification, but from what I gathered by looking at some files, it seems to be only necessary to check the "datapoints" tag. In there is a "startPosition" and "endPosition" tag and a "intensities" tag. The intensities give you the y-data, and the step for the x-data can be calculated from (endPosition-startPosition)/(number of datapoints).

I could probably write a python script to do this conversion for myself, but I think it would be a good idea to have this feature in xylib.

**Comment by wojdyr** [comment]
Yes, XRDML has been on the TODO list since the beginning - 10 years ago.

Could you attach an example data file that could be distributed with xylib?

I also haven't read the specs (or if I ever read them I don't remember anything), but looking at example files that I found on the internet I wonder how to handle multiple `<xrdMeasurement>` or `<scan>` tags? Merge, treat as separate datasets, or it depends?

Then the actual implementation would require some kind of XML parser. I think that to avoid extra dependencies one could use Boost Property Tree. I haven't used it before, but it should work fine:
http://www.boost.org/doc/libs/1_63_0/doc/html/property_tree/tutorial.html

**Comment by stupidus89** [comment]
Thanks for the reply.

I can upload an example file in a few days, I am currently a bit busy.

Indeed, multiple scans in a file are an issue. I guess that treating them as separate datasets would be the easiest way. How do you treat such cases in the other supported file formats? At least some of them should have the capability to store multiple datasets, don't they? Anyhow, I currently don't have any files with multiple scans, so I cannot test anything.

Unfortunately, I don't know anything about C++ or boost. In my quick and dirty python conversion script I am using the untangle library to parse the XML.

**Comment by wojdyr** [comment]
no need to hurry, I can find files for testing by googling filetype:xrdml
But it'd be good to have a file with a permission to distribute as an example.

**Comment by stupidus89** [comment]
I prepared a (very) simple example file.
[example.zip](https://github.com/wojdyr/xylib/files/768603/example.zip)

**Comment by wojdyr** [comment]
So I added basic support for XRDML. Each scan is interpreted as a separate dataset.
You are welcome to test it.
